- name: kill a session
  hosts: all
  vars:
    hostname:           "{{ p_host }}"
    port:               "{{ p_port }}"
    service_name:       "{{ p_service }}"
    username:           "{{ p_sysdba_un }}"
    password:           "{{ p_sysdba_pw }}"
    mode:               sysdba
    sid:                "{{ p_sid }}"
    serial:             "{{ p_serial }}"
    inst:               "{{ p_inst }}"

  tasks:
    - name: look for a session that matches the input parameters
      oracle_sql: 
        hostname:       "{{ hostname }}" 
        port:           "{{ port }}"
        service_name:   "{{ service_name }}"
        username:       "{{ username }}"
        password:       "{{ password }}"
        mode:           "{{ mode }}"
        sql:            >
                        select count(*) 
                        from   gv$session 
                        where  sid = '{{ sid }}'
                        and    serial# = '{{ serial }}'
                        and    inst_id = '{{ inst }}'
      register: p_count
      
    - name: show output status check (pre)
      debug:
        var: p_count.msg[0]
      
    - name: if the session exists, kill it
      block:
      - name: check existing status of session
        oracle_sql: 
          hostname:       "{{ hostname }}" 
          port:           "{{ port }}"
          service_name:   "{{ service_name }}"
          username:       "{{ username }}"
          password:       "{{ password }}"
          mode:           "{{ mode }}"
          sql:            >
                          select 'Session Exists', inst_id, sid, serial#, username, machine, program, logon_time, status 
                          from   gv$session 
                          where  sid = '{{ sid }}'
                          and    serial# = '{{ serial }}'
                          and    inst_id = '{{ inst }}'
        register: p_before
      
      - name: show output status check (pre)
        debug:
          var: p_before.msg[0]      
      
      - name: kill session
        debug:
          msg: "kill the session"
      when: 'p_count.msg[0].0 == 1'

    - name: if there's no matching session exists, we have nothing to kill
      block:
      - name: there was no matching session
        debug:
          msg: "there was no session in this instance with the specified SID and serial"
      when: 'p_count.msg[0].0 == 0'
