- name: manage a PDB
  hosts: all
  vars:
    hostname:           "{{ p_host }}"
    port:               "{{ p_port }}"
    service_name:       "{{ p_service }}"
    sourcedb:           "{{ p_cdb_name }}"
    pdbname:            "{{ p_pdb_name }}"
    username:           "{{ p_sysdba_un }}"
    password:           "{{ p_sysdba_pw }}"
    mode:               sysdba
    state:              "{{ p_state }}"
    oracle_home:        /u01/app/oracle/product/12.2.0/dbhome_1
    
  tasks:
    - name: put the pdb into the required state
      oracle_pdb: 
        hostname:       "{{ hostname }}"
        port:           "{{ port }}"
        service_name:   "{{ service_name }}"
        sourcedb:       "{{ sourcedb }}"
        name:           "{{ pdbname }}"
        username:       "{{ username }}"
        password:       "{{ password }}"
        mode:           "{{ mode }}"
        state:          "{{ state }}"
        oracle_home:    "{{ oracle_home }}"
      register: p_out
    - name: output
      debug:
        var: p_out.msg
    - name: get new service name
      oracle_sql: 
        hostname:       "{{ hostname }}" 
        port:           "{{ port }}"
        service_name:   "{{ service_name }}"
        username:       "{{ username }}"
        password:       "{{ password }}"
        sql:            >
                        select service_name 
                        from   v$services 
                        where  service_name like '%{{ pdbname }}%'
      register: p_new_service_name
      when: p_out.find('created') = 1
