
- name: Create a PDB
  hosts: all
  vars:
    hostname:           "{{ p_host }}"
    port:               "{{ p_port }}"
    service_name:       "{{ p_service }}"
    sourcedb:           "{{ p_cdb_name }}"
    pdbname:            "{{ p_pdb_name }}"
    username:           "{{ p_sysdba_un }}"
    password:           "{{ p_sysdba_pw }}"
    mode:               sysdba
    state:              present
    oracle_home:        /u01/app/oracle/product/12.2.0/dbhome_1
    
  tasks:
    - name: create the pdb
      oracle_pdb: 
        name:           "{{ pdbname }}"
        sourcedb:       "{{ sourcedb }}"
        state:          "{{ state }}"
        username:       "{{ username }}"
        password:       "{{ password }}"
        mode:           "{{ mode }}"
        service_name:   "{{ service_name }}"
        hostname:       "{{ hostname }}"
        oracle_home:    "{{ oracle_home }}"
