- name: kill a session
  hosts: all
  vars:
    hostname:           "{{ p_host }}"
    port:               "{{ p_port }}"
    service_name:       "{{ p_service }}"
    username:           "{{ p_sysdba_un }}"
    password:           "{{ p_sysdba_pw }}"
    mode:               sysdba
    sid:                "{{ p_sid }}"
    serial:             "{{ p_serial }}"
    inst:               "{{ p_inst }}"

  tasks:
    - name: check existing status of session
      oracle_sql: 
        hostname:       "{{ hostname }}" 
        port:           "{{ port }}"
        service_name:   "{{ service_name }}"
        username:       "{{ username }}"
        password:       "{{ password }}"
        mode:           "{{ mode }}"
        sql:            >
                        select 'Session Exists', inst_id, sid, serial#, username, machine, program, logon_time, status 
                        from   gv$session 
                        where  sid = '{{ p_sid }}'
                        and    serial# = '{{ p_serial }}'
                        and    inst_id = '{{ p_inst }}'
      register: p_before
      
    - name: show output status check (pre)
      debug:
        var: p_before.msg[0].0
      
    - name: iff the session exists, kill it
      block:
      - name: kill session
        debug:
          msg: "kill the session"
      when: "{{ p_before.msg[0].1 | search("Session Exists") }}"       # returns True if the specified session exists
