
- name: Create a PDB
  hosts: all
  vars:
    hostname:           cs-greybox-mvp-dbcs-1
    port:               1521    
    service_name:       APIPCS.588919103.oraclecloud.internal
    sourcedb:           APIPCS
    pdbname:            "{{ p_pdb_name }}"
    username:           sys
    password:           super45CS#
    mode:               sysdba
    state:              present
    oracle_home:        /u01/app/oracle/product/12.2.0/dbhome_1
    
  tasks:
    - name: create the pdb
      oracle_pdb: 
        name:           "{{ pdbname }}"
        sourcedb:       "{{ sourcedb }}"
        state:          "{{ state }}"
        username:       "{{ username }}"
        password:       "{{ password }}"
        mode:           "{{ mode }}"
        service_name:   "{{ service_name }}"
        hostname:       "{{ hostname }}"
        oracle_home:    "{{ oracle_home }}"
