- hosts: all
  user: opc
  become: yes
  become_user: oracle
  become_method: sudo
  vars:
    oraclehost:         "{{ p_host }}"
    oracleport:         "{{ p_port }}"
    oracleservice:      "{{ p_service }}"
    oracleuser:         "{{ p_dba_user }}"
    oraclepassword:     "{{ p_password }}"
    oracle_env:
      ORACLE_HOME:      /u01/app/oracle/product/12.2.0/dbhome_1
      LD_LIBRARY_PATH:  /u01/app/oracle/product/12.2.0/dbhome_1/lib
  tasks:
    - name: gather database facts
      oracle_facts:
        hostname:       "{{ oraclehost }}"
        port:           "{{ oracleport }}"
        service_name:   "{{ oracleservice }}"
        user:           "{{ oracleuser }}"
        password:       "{{ oraclepassword }}"
      register: dbfacts
    - debug:
        var: dbfacts
        
