
- name: Hello World Sample
  hosts: all
  sudo: yes
  sudo_user: opc  
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! - copied from the ansible-tower-samples GitHub repo"
