
- name: Hello World Sample
  hosts: all
  user: opc
  become: yes
  become_user: oracle  
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! - copied from the ansible-tower-samples GitHub repo"
    - name: Run Some Arbitrary Commands
      shell: echo "this playbook was executed by" $LOGNAME "at" $(date) >> /tmp/out
