
- name: Hello World Sample
  hosts: all
  user: root
  become: yes
  become_user: oracle
  become_method: sudo
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! - copied from the ansible-tower-samples GitHub repo"
