
- name: Hello World Sample
  hosts: all
  user: opc
  sudo: yes
  sudo_user: oracle
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! - copied from the ansible-tower-samples GitHub repo"
