
- name: Hello World Sample
  hosts: all
  vars:
    string_values: '{{ v_string }}'
  user: opc
  become: yes
  become_user: '{{ v_user }}' 
  become_method: sudo
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! - copied from the ansible-tower-samples GitHub repo"
    - name: Run Some Arbitrary Commands
      command: |
        echo "this playbook was executed by" $LOGNAME "at" $(date) "with string value" {{ item }}
      with_items: "{{ string_values }}"
      register: out
    - debug:
        var: "{{ string_values }}"
