
- name: Hello World Sample
  hosts: all
  vars:
    string_values:
      - string1
      - string2
  user: opc
  become: yes
  become_user: oracle  
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! - copied from the ansible-tower-samples GitHub repo"
    - name: Run Some Arbitrary Commands
      shell: |
        echo "this playbook was executed by" $LOGNAME "at" $(date) "with string value" {{ item }} >> /tmp/out
      with_items: string_values
