
- name: Hello World Sample
  hosts: all
  become: yes
  become_user: root  
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! - copied from the ansible-tower-samples GitHub repo"
